---
title: Project Review Template 
author: YOUR NAME
date: date-modified
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Working Status Analysis of H-1B Visa Workers Using H-1B LCA Disclosure Data (2020–2024)

Name of project author(s): Yufei Wu

Name of project reviewer: Alexis Gonzalez



# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

Interesting topic! The introduction section is just lacking a reason why or your motivation for analyzing H-1B visas. You can definitely mention the political climate and any changes that have been made to visas. Also why are we looking at wages, what informationa are you hoping to gain. (it is really interesting just needs some justification)

### Summary assessment 

* some contextualization and motivation



## Question description

### Feedback and Comments
Question and projet aims are clear just need justification for why these specific aims.

### Summary assessment

* question/hypotheses fully clear


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

Data is described well 

### Summary assessment
* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

- Good description of figures
- good array of EDA figures, I have a really good idea of the data in this dataset

### Summary assessment
* major weaknesses in wrangling and exploratory component
* some weaknesses in wrangling and exploratory component
* essentially no weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

Yes I think you chose the proper analysis methods. Random forest and XGboost were good choices

### Summary assessment
s 
* strong and reasonable analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

Results are easy to understand, I like that you described them as well.

### Summary assessment

* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

- Strong discussion section
- explained limitations to the predictive modeling
- discussion could use a couple senetences on implications of this study
### Summary assessment

* strong, complete and clear discussion


## Further comments

_Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project._



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

Project is well structured no unnecessary files.

### Summary assessment

* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

All code is well documented and easy to follow. I was able to find where each analysis started

### Summary assessment

* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

Reproducible. I could not load in the tables for the manuscript but that may just been an issue on my end. Make sure to check that before the final submission


### Summary assessment

* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

You used 3 different prediction models and found the strongest one I would call that pretty thorough.

### Summary assessment

* strong level of thorougness


## Further comments

This looks really good! There wa a typo here and there so be sure to clean that up before final submission.





